api/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('tester/', TesterAPI.as_view(), name='TesterAPI'),
    path('tester/<int:pk>/', TesterAPI.as_view(), name='TesterAPI'),

    path('company/', CompanyAPI.as_view(), name='CompanyAPI'),
    path('company/<int:pk>/', CompanyAPI.as_view(), name='CompanyAPI'),

    path('project/', ProjectAPI.as_view(), name='ProjectAPI'),
    path('project/<int:pk>/', ProjectAPI.as_view(), name='ProjectAPI'),

    path('hardware/', HardwareAPI.as_view(), name='HardwareAPI'),
    path('hardware/<int:pk>/', HardwareAPI.as_view(), name='HardwareAPI'),
]

frontend/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', SigninView, name='signin'),
    path('logout/', LogoutView, name="logout"),
    path('dashboard/', DashboardView, name='dashboard'),
    path('tester/', TesterView, name='tester'),
    path('tester/<int:pk>', TesterDetailsView, name="testerDetails"),
    path('company/', CompanyView, name='company'),
    path('company/<int:pk>', CompanyDetailsView, name="companyDetails"),
    path('project/', ProjectView, name='project'),
    path('project/<int:pk>', ProjectDetailsView, name="projectDetails"),
    path('hardware/', HardwareView, name='hardware'),
    path('hardware/<int:pk>', HardwareDetailsView, name="hardwareDetails"),
]

root/urls.py
from django.urls import path, include, re_path
# from django.views.generic import TemplateView

urlpatterns = [
    path('', include(('frontend.urls', 'frontend'), namespace='frontend')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]

# urlpatterns += [re_path(r'^.*', TemplateView.as_view(template_name='index.html'))]

api/models.py
from django.db import models

class TesterModel(models.Model):
    name = models.TextField(null=False, default=None)
    email = models.TextField(null=True, blank=True)
    phone_number = models.TextField(null=True, blank=True)
    
    def __str__(self):
        return self.name

class CompanyModel(models.Model):
    name = models.TextField(null=False, default=None)

    def __str__(self):
        return self.name

class ProjectModel(models.Model):
    name = models.TextField(null=False, default=None)
    company = models.ForeignKey(
        CompanyModel,
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return self.name

class HardwareModel(models.Model):
    tester = models.ForeignKey(
        TesterModel,
        on_delete=models.SET_NULL,
        null=True,
    )
    project = models.ForeignKey(
        ProjectModel,
        on_delete=models.SET_NULL,
        null=True,
    )
    name = models.TextField(null=False, default=None)

    STATUS_CHOICES = [
        ('Unassigned', 'Unassigned'),
        ('To be delivered', 'To be delivered'),
        ('Delivered', 'Delivered'),
        ('Returning', 'Returning'),
        ('Returned', 'Returned'),
        ('Kept', 'Kept')
    ]

    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='Unassigned')
    notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

templates/app/base.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<title>{% block title %}{% endblock %} | Hardware Management</title>

		<!-- Favicon -->
		<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />
		<!-- Bootstrap 5 CSS -->
		<link
			rel="stylesheet"
			type="text/css"
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
			crossorigin="anonymous"
		/>
		<!-- Datatable CSS -->
		<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" />
		<!-- Our Custom CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}" />
	</head>
	<body>
		{% include "app/header.html" %}
		<div class="container-fluid">
			<div class="row">
				{% include "app/sidebar.html" %}
				<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">{% block content %}{% endblock %}</main>
			</div>
		</div>

		<!-- Bootstrap JS -->
		<script
			type="text/javascript"
			language="javascript"
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
			crossorigin="anonymous"
		></script>
		<!-- JQuery -->
		<script
			type="text/javascript"
			language="javascript"
			src="https://code.jquery.com/jquery-3.6.0.js"
			integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
			crossorigin="anonymous"
		></script>
		<!-- Datatable -->
		<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
		{% block script %} {% endblock %}
	</body>
</html>

templates/app/company.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Company {% endblock %}

<!-- CONTENT -->

{% block content %} {% csrf_token %}
<section>
	<div class="row justify-content-md-center mt-3">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">
			<table id="table" class="table table-striped table-hover display" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</section>
<section>{% include "app/modal.html" %}</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script type="text/javascript" language="javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
	$(document).ready(function () {
		var endpoint = "{{ label }}";
		$(".table").dataTable({
			sScrollX: "100%",
			destroy: true,
			paging: true,
			searching: true,
			sort: true,
			responsive: true,
			ajax: {
				url: "{% url 'api:CompanyAPI' %}",
				method: "GET",
				headers: { "X-CSRFToken": $("input[name=csrfmiddlewaretoken]").val() },
				contentType: "application/json; charset=UTF-8",
				dataType: "json",
				dataSrc: "",
			},
			columns: [
				{ data: "id" },
				{ data: "name" },
				{
					data: "id",
					render: function (data, type, full, meta) {
						return '<a href="/company/' + data + '" class="btn btn-secondary btn-sm me-2" type="button"><span>Edit</span></a>';
					},
				},
				{
					data: "id",
					render: function (data, type, full, meta) {
						return (
							'<button class="btn btn-danger btn-sm" type="button" onclick="deleteObject(\'' +
							"{{ label }}" +
							"'," +
							data +
							')"><span>Delete</span></button>'
						);
					},
				},
			],

			columnDefs: [
				{ defaultContent: "", targets: [1] },
				{ bSortable: false, targets: [2, 3] },
				{ searchable: false, targets: [2, 3] },
			],
			lengthMenu: [
				[10, 25],
				[10, 25],
			],
			pageLength: 10,
		});
	});
</script>
{% endblock %}

templates/app/companyDetails.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Company {% endblock %}

<!-- CONTENT -->

{% block content %} {% csrf_token %}
<section>
	<div class="row justify-content-md-center mt-3">
		<h1 class="h3 mb-3 fw-normal">Company <span id="span_title"></span> Edit</h1>
	</div>
	<div class="row justify-content-md-center mt-3">
		<div id="form_edit" class="col-12 col-sm-12 col-md-12 col-lg-12">{{ form }}</div>
	</div>
	<div class="row justify-content-md-center mt-3">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">
			<button href="#" class="btn btn-primary" type="button" id="id_save_object" value="{{ label }}/{{ object_id }}">
				<span>Save</span>
			</button>
		</div>
	</div>
</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script type="text/javascript" language="javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
	$(document).ready(function () {
		$("#span_title").text($("#id_name").val());
	});

	$("#id_name").keyup(function () {
		$("#span_title").text($(this).val());
	});
</script>
{% endblock %}

templates/app/dashboard.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Dashboard {% endblock %}

<!-- CONTENT -->

{% block content %}
<section>
	<h1 class="h1 mb-3 fw-normal">Hardware Management</h1>
</section>
<section>
	<div class="row">
		<div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-3">
			<canvas id="hardware_Status_pie_chart" style="min-height: 250px; width: auto"></canvas>
		</div>
		<div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-3">
			<canvas id="hardware_Status_polar_area_chart" style="min-height: 250px; width: auto"></canvas>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
			<canvas id="hardware_Status_bar_chart" style="min-height: 250px; width: auto"></canvas>
		</div>
	</div>
</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type="text/javascript" language="javascript" src="{% static 'js/charts.js' %}"></script>

<script>
	$(document).ready(function () {
		hardwareStatusPieChart({{ hardwareStatusCount }});
		hardwareStatusPolarAreaChart({{ hardwareStatusCount }});
		hardwareStatusBarChart({{ hardwareStatusCount }});
	});
</script>
{% endblock %}

templates/app/hardware.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Hardware {% endblock %}

<!-- CONTENT -->

{% block content %} {% csrf_token %}
<section>
	<div class="row justify-content-md-center mt-3">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">
			<table id="table" class="table table-striped table-hover display" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th>ID</th>
						<th>Project</th>
						<th>Name</th>
						<th>Status</th>
						<th>Assigned Tester</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</section>
<section>{% include "app/modal.html" %}</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script type="text/javascript" language="javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
	$(document).ready(function () {
		$(".table").dataTable({
			sScrollX: "100%",
			destroy: true,
			paging: true,
			searching: true,
			sort: true,
			responsive: true,
			ajax: {
				url: "{% url 'api:HardwareAPI' %}",
				method: "GET",
				headers: { "X-CSRFToken": $("input[name=csrfmiddlewaretoken]").val() },
				contentType: "application/json; charset=UTF-8",
				dataType: "json",
				dataSrc: "",
			},
			columns: [
				{ data: "id" },
				{ data: "project_name" },
				{ data: "name" },
				{ data: "status" },
				{ data: "tester_name" },
				{
					data: "id",
					render: function (data, type, full, meta) {
						return '<a href="/hardware/' + data + '" class="btn btn-secondary btn-sm me-2" type="button"><span>Edit</span></a>';
					},
				},
				{
					data: "id",
					render: function (data, type, full, meta) {
						return (
							'<button class="btn btn-danger btn-sm" type="button" onclick="deleteObject(\'' +
							"{{ label }}" +
							"'," +
							data +
							')"><span>Delete</span></button>'
						);
					},
				},
			],

			columnDefs: [
				{ defaultContent: "", targets: [1, 2, 3, 4] },
				{ bSortable: false, targets: [5, 6] },
				{ searchable: false, targets: [5, 6] },
			],
			lengthMenu: [
				[10, 25],
				[10, 25],
			],
			pageLength: 10,
		});
	});
</script>
{% endblock %}

templates/app/hardwareDetails.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Hardware | Hardware Management {% endblock %}

<!-- CONTENT -->

{% block content %} {% csrf_token %}
<section>
	<div class="row justify-content-md-center mt-3">
		<h1 class="h3 mb-3 fw-normal">Hardware <span id="span_title"></span> Edit</h1>
	</div>
	<div class="row justify-content-md-center mt-3">
		<div id="form_edit" class="col-12 col-sm-12 col-md-12 col-lg-12">{{ form }}</div>
	</div>
	<div class="row justify-content-md-center mt-3">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">
			<button href="#" class="btn btn-primary" type="button" id="save_object" value="{{ label }}/{{ object_id }}">
				<span>Edit</span>
			</button>
		</div>
	</div>
</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script type="text/javascript" language="javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
	$(document).ready(function () {
		$("#span_title").text($("#id_name").val());
	});

	$("#id_name").keyup(function () {
		$("#span_title").text($(this).val());
	});
</script>
{% endblock %}

templates/app/header.html
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{% url "frontend:dashboard" %}">Hardware Management</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="w-100"></div>
    <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url "frontend:logout" %}">Sign out</a>
        </li>
    </ul>
</header>

templates/app/modal.html
<button href="" class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#Modal">
	<span>Create new</span>
</button>

<!-- Modal -->
<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title text-dark" id="ModalLabel">Create new {{ label }}</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<div class="modal-body" id="modalBody">
				{% for f in form %} {% if f.label %}
				<label>{{ f.label }}</label>
				{% endif %} {{ f }} {% endfor %}
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><strong>Close</strong></button>
				<button href="" class="btn btn-primary" type="button" id="id_create_modal" value="{{ label }}"><strong>Create</strong></button>
			</div>
		</div>
	</div>
</div>

<!-- Modal - Are you sure? -->
<div class="modal fade" id="confirmModal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title text-dark" id="confirmMessage"></h5>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-danger" id="confirmOk">Delete</button>
				<button type="button" class="btn btn-secondary" id="confirmCancel">Cancel</button>
			</div>
		</div>
	</div>
</div>

templates/app/project.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Project {% endblock %}

<!-- CONTENT -->

{% block content %} {% csrf_token %}
<section>
	<div class="row justify-content-md-center mt-3">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">
			<table id="table" class="table table-striped table-hover display" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Company</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</section>
<section>{% include "app/modal.html" %}</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script type="text/javascript" language="javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
	$(document).ready(function () {
		$(".table").dataTable({
			sScrollX: "100%",
			destroy: true,
			paging: true,
			searching: true,
			sort: true,
			responsive: true,
			ajax: {
				url: "{% url 'api:ProjectAPI' %}",
				method: "GET",
				headers: { "X-CSRFToken": $("input[name=csrfmiddlewaretoken]").val() },
				contentType: "application/json; charset=UTF-8",
				dataType: "json",
				dataSrc: "",
			},
			columns: [
				{ data: "id" },
				{ data: "name" },
				{ data: "company_name" },
				{
					data: "id",
					render: function (data, type, full, meta) {
						return '<a href="/project/' + data + '" class="btn btn-secondary btn-sm me-2" type="button"><span>Edit</span></a>';
					},
				},
				{
					data: "id",
					render: function (data, type, full, meta) {
						return (
							'<button class="btn btn-danger btn-sm" type="button" onclick="deleteObject(\'' +
							"{{ label }}" +
							"'," +
							data +
							')"><span>Delete</span></button>'
						);
					},
				},
			],

			columnDefs: [
				{ defaultContent: "", targets: [1, 2] },
				{ bSortable: false, targets: [3, 4] },
				{ searchable: false, targets: [3, 4] },
			],
			lengthMenu: [
				[10, 25],
				[10, 25],
			],
			pageLength: 10,
		});
	});
</script>
{% endblock %}

templates/app/projectDetails.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Project {% endblock %}

<!-- CONTENT -->

{% block content %} {% csrf_token %}
<section>
	<div class="row justify-content-md-center mt-3">
		<h1 class="h3 mb-3 fw-normal">Project <span id="span_title"></span> Edit</h1>
	</div>
	<div class="row justify-content-md-center mt-3">
		<div id="form_edit" class="col-12 col-sm-12 col-md-12 col-lg-12">{{ form }}</div>
	</div>
	<div class="row justify-content-md-center mt-3">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">
			<button href="#" class="btn btn-primary" type="button" id="id_save_object" value="{{ label }}/{{ object_id }}">
				<span>Save</span>
			</button>
		</div>
	</div>
</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script type="text/javascript" language="javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
	$(document).ready(function () {
		$("#span_title").text($("#id_name").val());
	});

	$("#id_name").keyup(function () {
		$("#span_title").text($(this).val());
	});
</script>
{% endblock %}

templates/app/sidebar.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
	<div class="position-sticky pt-3">
		<ul class="nav flex-column">
			<li class="nav-item">
				<a class="nav-link sidebar-item active" aria-current="page" href="{% url "frontend:dashboard" %}">
					<span data-feather="home"></span>
					Dashboard
				</a>
			</li>
			<li class="nav-item sidebar-item">
				<a class="nav-link" href="{% url "frontend:tester" %}">
					<span data-feather="file"></span>
					Tester
				</a>
			</li>
			<li class="nav-item sidebar-item">
				<a class="nav-link" href="{% url "frontend:company" %}">
					<span data-feather="shopping-cart"></span>
					Company
				</a>
			</li>
			<li class="nav-item sidebar-item">
				<a class="nav-link" href="{% url "frontend:project" %}">
					<span data-feather="users"></span>
					Project
				</a>
			</li>
			<li class="nav-item sidebar-item">
				<a class="nav-link" href="{% url "frontend:hardware" %}">
					<span data-feather="bar-chart-2"></span>
					Hardware
				</a>
			</li>
		</ul>
	</div>
</nav>

templates/app/tester.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Tester {% endblock %}

<!-- CONTENT -->

{% block content %} {% csrf_token %}
<section>
	<div class="row justify-content-md-center mt-3">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">
			<table id="table" class="table table-striped table-hover" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th>ID</th>
						<th>Name</th>
						<th>Email</th>
						<th>Phone Number</th>
						<th></th>
						<th></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</section>
<section>{% include "app/modal.html" %}</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script type="text/javascript" language="javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
	$(document).ready(function () {
		$(".table").dataTable({
			sScrollX: "100%",
			destroy: true,
			paging: true,
			searching: true,
			sort: true,
			responsive: true,
			ajax: {
				url: "{% url 'api:TesterAPI' %}",
				method: "GET",
				headers: { "X-CSRFToken": $("input[name=csrfmiddlewaretoken]").val() },
				contentType: "application/json; charset=UTF-8",
				dataType: "json",
				dataSrc: "",
			},
			columns: [
				{ data: "id" },
				{ data: "name" },
				{ data: "email" },
				{ data: "phone_number" },
				{
					data: "id",
					render: function (data, type, full, meta) {
						return '<a href="/tester/' + data + '" class="btn btn-secondary btn-sm me-2" type="button"><span>Edit</span></a>';
					},
				},
				{
					data: "id",
					render: function (data, type, full, meta) {
						return (
							'<button class="btn btn-danger btn-sm" type="button" onclick="deleteObject(\'' +
							"{{ label }}" +
							"'," +
							data +
							')"><span>Delete</span></button>'
						);
					},
				},
			],

			columnDefs: [
				{ defaultContent: "", targets: [1, 2, 3] },
				{ bSortable: false, targets: [4, 5] },
				{ searchable: false, targets: [4, 5] },
			],
			lengthMenu: [
				[10, 25],
				[10, 25],
			],
			pageLength: 10,
		});
	});
</script>
{% endblock %}

templates/app/testerDetails.html
{% extends 'app/base.html' %} {% load static %} {% block title %} Tester {% endblock %}

<!-- CONTENT -->

{% block content %} {% csrf_token %}
<section>
	<div class="row justify-content-md-center mt-3">
		<h1 class="h3 mb-3 fw-normal">Tester <span id="span_title"></span> Edit</h1>
	</div>
	<div class="row justify-content-md-center mt-3">
		<div id="form_edit" class="col-12 col-sm-12 col-md-12 col-lg-12">{{ form }}</div>
	</div>
	<div class="row justify-content-md-center mt-3">
		<div class="col-12 col-sm-12 col-md-12 col-lg-12">
			<button href="#" class="btn btn-primary" type="button" id="id_save_object" value="{{ label }}/{{ object_id }}">
				<span>Save</span>
			</button>
		</div>
	</div>
</section>
{% endblock %}

<!-- SCRIPTS -->

{% block script %}
<script type="text/javascript" language="javascript" src="{% static 'js/ajax.js' %}"></script>
<script>
	$(document).ready(function () {
		$("#span_title").text($("#id_name").val());
	});

	$("#id_name").keyup(function () {
		$("#span_title").text($(this).val());
	});
</script>
{% endblock %}